language: java
jdk:
  - oraclejdk8
env:
  global:
    - secure: "n22q430GBtgZ4yR0BhKXuP+mrdv4QIQGO8uoM9Og1Orv8qdDJQWY94NB/d+ZrzfPZmBNnjFpRbCWBnTB3JRRtUl/WvvFQiWEkEe4x+ec/KdYPhg0tNScBeokoC9hT+OZUnO8gSj/4zfVegV2fEb7s6htkpt+c3mFHPz7v/ypUe9TB2ck/06dPuuiWEiwihSs63J+C0CC6vwF6dWrBnMUe6rs19O6TSCJZ1KhUwLbtoARHesgMY65lPFnqGOI874WCTcKBwN1PT1AIwSrdwxQozdvtxGCBt+w4rlISDQVgaHg0FK7Ij0vbmUKmrH0SmemzYXc2igDI+za4dvolVTNJ8nYsKQt54tFrAuM4zJpWkzdf6aUztFqxxfNjyLHbkjT91CaFUR3NDQ0LdxhbtZupe3T0/tkAPNQu72wrN+aQFU5zJdaJWpkB06mlsEusnLp1T+jo9ZlzwZb52G9SIG0y8BvdLHEHUx861YB8uc6br8m4rxCNpPQBDhaTm1sFVxLzxLoerNB20Q6oSQL9+IYuFaUvP1K19hB998e/r7Oe68bE3zzAbWN7ilyoK626p8YXq1HYA8n1tdKMKSPaNseJaFqPu1tOzjHiz5AunakFik8z7CQxO4t6KsTjwJn6FAa2b29jRz/Jyw8bVBuQglZAK/mJXlOcg3ebkXKHJvNBuo="
    - secure: "gUZyFPklqxoKaU1vRLjNmdsqv2pvmyQkPVJZU/dYTruFJgKtZkrK1WnBAa0MyaOsRbQC6TWNzunVEo4QLlG/F9NrQ0mpFGIcZ6zU/y+tdULJubdXATn0RdA8EqxH4lY0/D2CUJyqGfeHii59/dG33K/H1OkqyY9CZ4OhLFCur4rcR/6CtdQSIv496x6bKGJP+sjNpxJ8+6Ct22pcof6YAASuBX0JodHRDmQlSJcb710OWgL6BSzywgyALysFMz0pe/jHq9COBuLQ2bfcvZOT3GF4+n1DPw9p9+TxcUsgwWPjDhT19V472smdNH+dbHog1FEKsg7vVZNDfNMrEDxbqxdku4c/hg+EEAA1vbqH1P/KxBtdMXifMqnmMMBfQ/1MFM3OqAaj01/HVlkpgp0lAWQUGMVLkT16S17vZpBBFohuXteptO/5psypxu0pfI0kkgIZfwISEr5IICfX2/pDlBbfPXuWh+sshI8ctaMlYtRV2ScRDbsxjL8pVIxX37LE0nqVUTVFTrEo6tfxuANnleTyxGHUxxQ+YQH1kuWfz8uqJ5er/kjRWkHxy+kL5zlru+a641JUaYw9V2zJNeT2R4sLdKxQDNdFu09LhyuR84H5ZPfPCHZdOgylGHNN+ZTcdz7I4poqK3k/yy2YVgeOTKsoSCNxAgYR9p1nR6ficW8="
    - secure: "tPQsaf8jtJaoi5umERewg5p3NohW+CYyzSN+WQtsbBdnGsfpmZ8Hsqc5nwv9fhnL7NA0UDnO+DLVzSA9Q5jioCQa+M+hvV2LEfbxFoMNYLEzkyWlGPy9gWrLz0E9OomDuYiBZbFfw+jDQjLNAlAiKiaDkidvdiglIiNVEDDCRgQLAEu0KHIaTDcg6L22z3kumWtVL0q7rExPK3ciGWFeRi94a+4tcpG2sjfea4GkzD4SYQALS+YLWQJhDETtU1lbxNau+ueVkY92tCQDd4HwxEyufq81Psc2khBSpVFNuz7s816rhYS1YC9hUgbaNdkyk02bTH1eQSQHgd/IEYubXzlQCqF2MxFjzxwcd4B+HVk+a+Kz2S2h+HvoTw5/JnKVjjgszDTDp65oACJzm1OiaqmAOt7u3lPesJnUNsmAVLhJZ5TgE8+N4rp/P0v//6pT/zJ6gciyIittvYOPersPuwZ9vBOLA8N0eA1ykbWP69MV0ktDEa5O0vqVPC0tyTCmbaSdC9LTaQwxkoXASzX8pYnEeMekUjiH0pNQ61Famd92l4Ae/wyVJcynoUO/jNTu2WvO61++PSYKAJDuY8ukZxI2CXcfblsnpUOoyk3iqmhOwuYU9v58ifQCP9H8mEhwuoi1ATF4Nqh90SKGc37xgr6sidLoE0A6qhHq1rCzm2Q="
cache:
  directories:
    - $HOME/.gradle/caches
    - $HOME/.m2
before_script:
  - git clone https://github.com/etki/dummy-api-server.git /tmp/dummy-api-server
  - gradle -p /tmp/dummy-api-server bootRepackage
  - java -jar /tmp/dummy-api-server/build/libs/dummy-api-server*.jar &
  - echo $! > /tmp/dummy-api-server.pid
  - sleep 15
script:
  - gradle -version
  - gradle test
  - gradle acceptanceTest
after_success:
  - test "$TRAVIS_PULL_REQUEST" == "false" && gradle publish || echo 'Skipping publish due to pull request'
after_script:
  - kill $(cat /tmp/dummy-api-server.pid)