language: java
jdk:
  - oraclejdk8
cache:
  directories:
    - $HOME/.gradle/caches
    - $HOME/.m2
before_script:
  - git clone https://github.com/etki/dummy-api-server.git /tmp/dummy-api-server
  - gradle -p /tmp/dummy-api-server bootRepackage
  - java -jar /tmp/dummy-api-server/build/libs/dummy-api-server*.jar
script:
  - gradle -version
  - gradle test
  - gradle acceptanceTest